const crypto = require('crypto');
const fs = require('fs');
const path = require('path');
const readline = require('readline');

const ITERATIONS = 100000;
const KEY_LENGTH = 32;
const SALT_LENGTH = 16;
const IV_LENGTH = 12;

const rl = readline.createInterface({
    input: process.stdin,
    output: process.stdout
});

rl.question('Enter the password to encrypt the data: ', (password) => {
    rl.close();

    if (!password || password.trim().length === 0) {
        console.error('Password cannot be empty!');
        process.exit(1);
    }

    const dataPath = path.join(__dirname, '..', 'data', 'wedding-data.json');
    const outputPath = path.join(__dirname, '..', 'js', 'encrypted-data.js');

    if (!fs.existsSync(dataPath)) {
        console.error('File not found: ' + dataPath);
        console.error('Create the file data/wedding-data.json with the wedding data.');
        process.exit(1);
    }

    const jsonData = fs.readFileSync(dataPath, 'utf8');

    try {
        JSON.parse(jsonData);
    } catch (e) {
        console.error('Invalid JSON file:', e.message);
        process.exit(1);
    }

    const salt = crypto.randomBytes(SALT_LENGTH);
    const iv = crypto.randomBytes(IV_LENGTH);
    const key = crypto.pbkdf2Sync(password, salt, ITERATIONS, KEY_LENGTH, 'sha256');

    const cipher = crypto.createCipheriv('aes-256-gcm', key, iv);
    let encrypted = cipher.update(jsonData, 'utf8');
    encrypted = Buffer.concat([encrypted, cipher.final()]);
    const tag = cipher.getAuthTag();

    // Web Crypto API AES-GCM expects ciphertext || authTag
    const combined = Buffer.concat([encrypted, tag]);

    const output = [
        '// Auto-generated by scripts/encrypt.js — do not edit manually',
        'const ENCRYPTED_DATA = {',
        '  salt: "' + salt.toString('base64') + '",',
        '  iv: "' + iv.toString('base64') + '",',
        '  data: "' + combined.toString('base64') + '"',
        '};',
        ''
    ].join('\n');

    fs.writeFileSync(outputPath, output, 'utf8');

    console.log('Data encrypted successfully!');
    console.log('Output file: ' + outputPath);
    console.log('Size: ' + jsonData.length + ' → ' + combined.length + ' bytes (encrypted)');
});
